### PR TITLE
Add support for openfl/lime

### PR DESCRIPTION
**Pull request by mrcdk**
I've only tested it with this sample https://github.com/ncannasse/heaps/tree/master/samples/basic

The `hxml` to get it to work is:
```
-cpp bin
-main Main
-lib heaps
-lib openfl
-lib lime

-D lime-openal
-D openfl-next
-D lime-cairo
-D lime-opengl
-D native
-D lime-native
-D lime-curl
-D openfl-native
-D windows
-D desktop


-D resourcesPath=../res
--macro include('h3d')
--remap flash:openfl
```
And I had to comment out these lines for it to run:
https://github.com/ncannasse/heaps/blob/master/h3d/shader/AmbientLight.hx#L31
https://github.com/ncannasse/heaps/blob/master/h3d/shader/AmbientLight.hx#L35
https://github.com/ncannasse/heaps/blob/master/hxsl/Linker.hx#L365

### CODE REVIEW

**Comment by ncannasse** [comment]
Thanks !
The three commented lines are related to #115, will be fixed soon

**Comment by kevinresol** [comment]
Does this mean openfl native extensions can be used with heaps?

**Comment by mrcdk** [comment]
@kevinresol I don't think so, not without the lime build system. I haven't tried to use it with heaps and see how ~~my computer explodes~~ they work together. The lime build system is also used in some targets (android, iOS) to create the final executable, so getting it to work with heaps is needed. I'll try it soon.

It may be possible to remove openfl from the equation altogether... I will investigate this too.

**Comment by delahee** [comment]
Well it should, our workflow at MT was openfl native extension + h3d which
is pretty much the same as heaps so yes it can definitely work and used to
in our case.

2015-10-21 19:40 GMT+02:00 Justo Delgado <notifications@github.com>:

> @kevinresol <https://github.com/kevinresol> I don't think so, not without
> the lime build system. I haven't tried to use it with heaps and see how my
> computer explodes they work together. The lime build system is also used
> in some targets (android, iOS) to create the final executable, so getting
> it to work with heaps is needed. I'll try it soon.
>
> It may be possible to remove openfl from the equation altogether... I will
> investigate this too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncannasse/heaps/pull/123#issuecomment-149973272>.
>



-- 
David Elahee

**Pull request merged**
