### PR TITLE
Console hide, show and fix log

### PR DESCRIPTION
**Pull request by hammeron-art**
Let hide and show by code.
The log wasn't working with Haxe 3.2.1 because the UString class and this: https://github.com/HaxeFoundation/haxe/issues/4426

### CODE REVIEW

**Comment by ncannasse** [comment]
What's the regexp for ? It seems to somehow restrict arguments values, not sure I want it :)

**Comment by hammeron-art** [comment]
It doesn't restrict arguments.
I made it to match regular arguments and strings with spaces. http://regexr.com/3d58g
I put some extra things like (?:['|"]) to match but don't capture quotes but Haxe regex don't expose functions to deal with capture groups.

**Comment by ncannasse** [comment]
The regexp cause some problem, for instance if you do `/command myfile.png` it will split in two `myfile` and `png`

**Comment by hammeron-art** [comment]
Yeah, can't use regex at all for this.
Now with a loop it works for symbols too.

**Pull request merged**
