### PR TITLE
Timer improvements

### PR DESCRIPTION
**Pull request by sepharoth213**
I noticed that the timer was making my timers inaccurate with respect to real time, so I added an option for turning the `deltaT` smoothing off.

I also fixed a bug where if `deltaT` was greater than `maxDeltaTime`, it would fall back to the previous frame's `calc_tmod`.

### CODE REVIEW

**Comment by ncannasse** [comment]
I think you can already disable smoothing by setting tmod_factor=0

**Comment by sepharoth213** [comment]
Ah, that's what the code was intended to do. I've changed it so that setting `tmod_factor` to 0, it will behave as if there was no smoothing. For some reason, heaps had previously had `(1 - tmod_factor) * deltaT * wantedFPS`, making the reported dt really broken. That's where the issues I was having with timing were coming from.

I also fixed fps() reporting `wantedFPS` times the current framerate rather than the actual current framerate.

**Comment by ncannasse** [comment]
I don't want to change calc_tmod at all, the idea of the tmod is that is should = 1 when your actual FPS  match the wantedFPS.

**Comment by sepharoth213** [comment]
I was confused because App calls update with tmod passed in as dt: `update(hxd.Timer.tmod);`
I assumed that meant it was supposed to be some other form of deltaT.

Is that intended as well?

**Comment by ncannasse** [comment]
Yes

**Pull request closed without merging**
