### PR TITLE
Fix textWidth with align Center, Right

### PR DESCRIPTION
**Pull request by Tipyx**

### CODE REVIEW

**Comment by ncannasse** [comment]
Could you resubmit with clean changes (no newline/spaces changes) ?
Also, I don't understand the change: calcWidth needs to be written whatever the alignment

**Comment by Tipyx** [comment]
Yep, but when you update the text with align Center or Right, calcWidth = realTextWidth + x (which is needed by getBoundsRec), it's why I separate the values in two differents parameters :
- calcWidth : the real size of the text (regardless of the Align)
- calcXMax : calcWidth + offsetX

**Comment by ncannasse** [comment]
I see. You still need to save/restore calcXMax in calcTextWidth

**Comment by Tipyx** [comment]
It's done.

**Comment by ncannasse** [comment]
This breaks h2d.Flow, I have no idea why so I reverted for now

**Pull request merged**
